services:
  - type: web
    name: n8n-service
    env: docker
    plan: starter
    autoDeploy: true
    image: quanquanhoang/n8n-puppeteer:latest
    envVars:
      - key: N8N_HOST
        value: n8n-service-5sd4.onrender.com
      - key: N8N_PORT
        value: 443
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_ENDPOINT_WEBHOOK
        value: webhook
      - key: N8N_ENDPOINT_WEBHOOK_TEST
        value: webhook-test
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-service-5sd4.onrender.com/webhook
				 - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
